extends:
    - next/core-web-vitals

plugins:
    - unused-imports

rules:
    unused-imports/no-unused-imports: warn
    linebreak-style:
        - error
        - unix
    jsx-quotes:
        - error
        - prefer-double

    quotes: 0
    react/display-name: 0
