services:
  band-manager-db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "strongpassword"
      MYSQL_DATABASE: "band-manager"
    volumes:
      - ./db_data:/var/lib/mysql:rw